#version: '2'
#
services:
  redis:
    image: 'rabbitmq:latest'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '8080:8080'
        #volumes:
        #  - 'rabbitmq:/bitnami/redis/data'

        #volumes:
        #  redis_data:
        #    driver: local
        #
version: '2'
services:
  rabbitmq:
    container_name: some-rabbitmq
    image: launcher.gcr.io/google/rabbitmq3
    environment:
      #"RABBITMQ_ERLANG_COOKIE": "unique-erlang-cookie"
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '25672:25672'
